### PR TITLE
Add confirmation email sending

### LINKED ISSUE #38: Add Email Auto Response to Contact Form
As a San Jose Census 2020 kiosk user, I want an email response to any contact form so that I will know my request was received and that someone will answer.

Acceptance Criteria
- When a form is submitted, an email is automatically sent to the email entered by the requester.
- The email begins with the name entered, thanks the user, and lists their response to the Interest question and any comments. It ends with a statement that someone will respond within two business days.
- The standard strings will be translated if the requester was on the Spanish or Vietnamese version of the page.

### PR DESCRIPTION
**Pull request by turnerhayes**
Fixes #38.

### CODE REVIEW

**Comment by turnerhayes** [comment]
- Email formatting could use a little (lot?) of love
- Need to figure out how to do i18n on the subject and message content
  - A bit trickier since this is server-side, so the existing i18n solution doesn't necessarily transfer all that well.

**Comment by JMStudiosJoe** [comment]
Is this still WIP or ready for review?

**Review by JMStudiosJoe — APPROVED** [review]

**Comment by turnerhayes** [comment]
There are a few minor copy changes that @aelar13 made that are not yet reflected in the code, but other than that it should be ready.

**Comment by turnerhayes** [comment]
Oh, and also the i18n, although that can probably be done in a separate PR.

**Pull request merged**
